name: episode_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  google_fonts: ^6.2.1
  blur: ^4.0.0
  skeletonizer: ^1.4.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets: 
    - assets/data/
    - assets/images/
